# Retrieval Evaluation

Evaluate fuzzy and semantic retrieval for the TM store.

In [52]:
import os
import sys

sys.path.append(os.path.join(os.getcwd(), "..", "src"))
from retrieve import load_translation_memory, fuzzy_retrieval, semantic_retrieval
from sentence_transformers import SentenceTransformer
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct
from qdrant_client.http import models
import uuid
import json
import pandas as pd

In [53]:
# Importing the translation memory
tm = load_translation_memory("../data/tm/translation_memory.jsonl")

In [54]:
# Initializing model and client
model = SentenceTransformer("all-MiniLM-L6-v2")
client = QdrantClient(url="http://localhost:6333")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5596.53it/s]

In [55]:
# Converting gold_set to pandas df

gold_set = pd.read_json("../eval/gold_set.jsonl", lines=True)
gold_set.head()

,case_id,category,query,reference,edit_type,requires_agreement,flag,comment,previous_source,target_approved,source_file,base_id,source,target,acceptable_ids
0,f01,fuzzy_real,Pirate Flagship,Okręt flagowy piratów,reworded,no,ok,NaN,Fire Wraith,Ogniste widmo,pl_units.po,NaN,NaN,NaN,NaN
1,f02,fuzzy_real,plague ($type),zaraza ($type),addition,no,ok,NaN,plague,zaraza,pl_help.po,NaN,NaN,NaN,NaN
2,f03,fuzzy_real,Campaigns and Scenarios,Kampanie i scenariusze,tag/formatting,no,target_error,"It seems that ""Scenariusze"" shouldn't be capit...",<header>text='Campaigns and Scenarios'</header>,<header>text='Kampanie i Scenariusze'</header>,pl_help.po,NaN,NaN,NaN,NaN
3,f04,fuzzy_real,<ref>dst='..calendar' text='Calendar'</ref>\n<...,<ref>dst='..calendar' text='Kalendarz'</ref>\n...,addition,no,ok,NaN,<ref>dst='..geography' text='Geography'</ref>,<ref>dst='..geography' text='Geografia'</ref>,pl_help.po,NaN,NaN,NaN,NaN
4,f05,fuzzy_real,Time of Day Schedule,Grafik pór dnia,addition,yes,ok,NaN,Time of Day,Pora dnia,pl_help.po,NaN,NaN,NaN,NaN

In [56]:
# Filtering for edited category
gold_set_edited = gold_set[gold_set['category'] == 'edited']
gold_set_edited.head()

,case_id,category,query,reference,edit_type,requires_agreement,flag,comment,previous_source,target_approved,source_file,base_id,source,target,acceptable_ids
30,e01,edited,Water Drake,Smok wody,term,yes,ok,NaN,NaN,NaN,pl_units.po,ad6556ad9d1a7c5490aeee99cd5ae37f,Sky Drake,Smok przestworzy,[ad6556ad9d1a7c5490aeee99cd5ae37f]
31,e02,edited,This option directly connects you to the offic...,Ta opcja umożliwia połączenie się z oficjalnym...,reworded,yes,ok,Difficult agreement problem,NaN,NaN,pl_manual.po,f94cea635a476d688c00d55547dc991d,This option directly connects you to the offic...,Ta opcja umożliwia połączenie się z oficjalnym...,[f94cea635a476d688c00d55547dc991d]
32,e03,edited,Royal Architect,Królewski architekt,term,yes,ok,NaN,NaN,NaN,pl_units.po,be44cca919aed8f7ff929d174f33dbc5,Royal Warrior,Królewski wojownik,[be44cca919aed8f7ff929d174f33dbc5]
33,e04,edited,Dune Raider,Wydmowy jeździec,term,yes,ok,NaN,NaN,NaN,pl_units.po,582cac393fe26ef975ab0f963a5b6904,Dune Explorer,Wydmowy odkrywca,[582cac393fe26ef975ab0f963a5b6904]
34,e05,edited,Second Watch — fourth hour,Druga straż – czwarta godzina,reworded,no,ok,NaN,NaN,NaN,pl_help.po,6072f0716794dbd6ee7a93bef92b2e73,First Watch — Fourth Hour,Pierwsza straż — czwarta godzina,[6072f0716794dbd6ee7a93bef92b2e73]

In [57]:
# Counting the number of edited records
edited_count = gold_set_edited['query'].count()
print(f"Number of edited records: {edited_count}")

Number of edited records: 30

## Helper functions for metrics calculations

In [58]:
# Id ranking for fuzzy matches
test_query = gold_set_edited.iloc[0]['query']
print(test_query)

Water Drake

In [59]:
test_retrieval = fuzzy_retrieval(tm, test_query, 1)
print(test_retrieval[0][0])

66.66666666666667

In [60]:
def ranked_ids_fuzzy(query, k) -> list[str]:
    """Function returning top k id from fuzzy retrieval"""
    result = fuzzy_retrieval(tm, query, k)
    records = []
    for score, record in result:
        records.append(record['id'])
        
    return records

ranked_id_test = ranked_ids_fuzzy(test_query, 7)
print(ranked_id_test)

['6cc6bb3c77c7d12c68c0f9ad48ca457c', 'b3f504f9f5b11d7adfcf5fa81e2a7964', '58ecb10d84b4884e1657a76a7b2c152f', '5daef117699a4902980a91cf2216b740', 'dd99398ff131f3b1ecb26a578074b525', 'b8e903d5dd4c486bf3b2c7a418fc6841', '4d28cd285b4ee125e32741cfa188c0f9']

In [61]:
# Id ranking for semantic retrieval

def ranked_ids_semantic(query, k) -> list[str]:
    """Function returning top k id from semantic retrieval"""
    tm_index = {r["id"]: r for r in tm}
    result = semantic_retrieval(query, tm_index, model, client, k)
    records = []
    for score, record in result:
        records.append(record['id'])
            
    return records

ranked_id_semantic_test = ranked_ids_semantic(test_query, 7)
print(ranked_id_semantic_test)

['4d28cd285b4ee125e32741cfa188c0f9', 'a56c33315fdac1fb59947d3bd8689aaa', 'b3f504f9f5b11d7adfcf5fa81e2a7964', '649d435a01b5556d3cb137ceff202c24', 'ad6556ad9d1a7c5490aeee99cd5ae37f', 'c01826dddbd7ff74d6b3c4a0b847f380', '5daef117699a4902980a91cf2216b740']

In [62]:
# Does ranked_id exist in acceptable_id list?
for i in ranked_id_semantic_test:
    if i in gold_set_edited.iloc[0]['acceptable_ids']:
        print(True)
    else:
        print(False)

False
False
False
False
True
False
False

In [63]:
def hit(ranked_ids, acceptable_ids, k) -> bool:
    """Returns true if any ranked_id exists in acceptable_ids - correct retrieval hit"""
    return any(s in acceptable_ids for s in ranked_ids[:k])

In [64]:
acceptable_ids_test = gold_set_edited.iloc[0]['acceptable_ids']
print(hit(ranked_id_semantic_test, acceptable_ids_test, 7))

True

In [65]:
print(ranked_id_semantic_test)
for i in ranked_id_semantic_test:
    if i in gold_set_edited.iloc[0]['acceptable_ids']:
        rank = ranked_id_semantic_test.index(i)
        print(1/rank)

['4d28cd285b4ee125e32741cfa188c0f9', 'a56c33315fdac1fb59947d3bd8689aaa', 'b3f504f9f5b11d7adfcf5fa81e2a7964', '649d435a01b5556d3cb137ceff202c24', 'ad6556ad9d1a7c5490aeee99cd5ae37f', 'c01826dddbd7ff74d6b3c4a0b847f380', '5daef117699a4902980a91cf2216b740']
0.25

In [66]:
def reciprocal_rank(ranked_ids, acceptable_ids) -> float:
    for pos, id in enumerate(ranked_ids, start=1):
        if id in acceptable_ids:
            return 1/pos
    return 0.0

## Evaluation

In [67]:
# Setting up the necessary variables
top_k = 5
results = []

In [68]:
for _, row in gold_set_edited.iterrows():
    print(row)

case_id                                              e01
category                                          edited
query                                        Water Drake
reference                                      Smok wody
edit_type                                           term
requires_agreement                                   yes
flag                                                  ok
comment                                              NaN
previous_source                                      NaN
target_approved                                      NaN
source_file                                  pl_units.po
base_id                 ad6556ad9d1a7c5490aeee99cd5ae37f
source                                         Sky Drake
target                                  Smok przestworzy
acceptable_ids        [ad6556ad9d1a7c5490aeee99cd5ae37f]
Name: 30, dtype: object
case_id                                                             e02
category                                                         edited
query                 This option directly connects you to the offic...
reference             Ta opcja umożliwia połączenie się z oficjalnym...
edit_type                                                      reworded
requires_agreement                                                  yes
flag                                                                 ok
comment                                     Difficult agreement problem
previous_source                                                     NaN
target_approved                                                     NaN
source_file                                                pl_manual.po
base_id                                f94cea635a476d688c00d55547dc991d
source                This option directly connects you to the offic...
target                Ta opcja umożliwia połączenie się z oficjalnym...
acceptable_ids                       [f94cea635a476d688c00d55547dc991d]
Name: 31, dtype: object
case_id                                              e03
category                                          edited
query                                    Royal Architect
reference                            Królewski architekt
edit_type                                           term
requires_agreement                                   yes
flag                                                  ok
comment                                              NaN
previous_source                                      NaN
target_approved                                      NaN
source_file                                  pl_units.po
base_id                 be44cca919aed8f7ff929d174f33dbc5
source                                     Royal Warrior
target                                Królewski wojownik
acceptable_ids        [be44cca919aed8f7ff929d174f33dbc5]
Name: 32, dtype: object
case_id                                              e04
category                                          edited
query                                        Dune Raider
reference                               Wydmowy jeździec
edit_type                                           term
requires_agreement                                   yes
flag                                                  ok
comment                                              NaN
previous_source                                      NaN
target_approved                                      NaN
source_file                                  pl_units.po
base_id                 582cac393fe26ef975ab0f963a5b6904
source                                     Dune Explorer
target                                  Wydmowy odkrywca
acceptable_ids        [582cac393fe26ef975ab0f963a5b6904]
Name: 33, dtype: object
case_id                                              e05
category                                          edited
query                         Second Watch — fourth hour
reference                  Druga straż – czwarta godzina
edit_type                                       reworded
requires_agreement                                    no
flag                                                  ok
comment                                              NaN
previous_source                                      NaN
target_approved                                      NaN
source_file                                   pl_help.po
base_id                 6072f0716794dbd6ee7a93bef92b2e73
source                         First Watch — Fourth Hour
target                  Pierwsza straż — czwarta godzina
acceptable_ids        [6072f0716794dbd6ee7a93bef92b2e73]
Name: 34, dtype: object
case_id                                                             e06
category                                                         edited
query                 Saurians are very small of frame, and though t...
reference             Jaszczury są bardzo drobnej budowy, lecz pomim...
edit_type                                                      reworded
requires_agreement                                                   no
flag                                                       target_error
comment               Grammar error in the original target "trudnym ...
previous_source                                                     NaN
target_approved                                                     NaN
source_file                                                 pl_units.po
base_id                                c9719b33c07a2fa6cc0491f865ffe17e
source                Saurians are very small of frame, and though t...
target                Jaszczury są bardzo drobnej budowy, lecz pomim...
acceptable_ids                       [c9719b33c07a2fa6cc0491f865ffe17e]
Name: 35, dtype: object
case_id                                                             e07
category                                                         edited
query                 Game maps feature a variety of terrains that a...
reference             Na mapach poszczególnych scenariuszy występuje...
edit_type                                                        number
requires_agreement                                                  yes
flag                                                       target_error
comment               Mistranslation in the original target (combat ...
previous_source                                                     NaN
target_approved                                                     NaN
source_file                                                  pl_help.po
base_id                                588517c38e2e5a827671c0d113d0a53f
source                Game maps feature a variety of terrains that a...
target                Na mapach poszczególnych scenariuszy występuje...
acceptable_ids                       [588517c38e2e5a827671c0d113d0a53f]
Name: 36, dtype: object
case_id                                                             e08
category                                                         edited
query                 A final blow destroys the lich, releasing a sm...
reference             Ostateczny cios niszczy liczę, uwalniając nagł...
edit_type                                                        gender
requires_agreement                                                  yes
flag                                                       target_error
comment               Very difficult example as the term "lich" was ...
previous_source                                                     NaN
target_approved                                                     NaN
source_file                                                  pl_httt.po
base_id                                e506af756501c84e2129385c9f788fdf
source                A final blow destroys the lich, releasing a sm...
target                Ostateczny cios niszczy licza, uwalniając nagł...
acceptable_ids                       [e506af756501c84e2129385c9f788fdf]
Name: 37, dtype: object
case_id                                                             e09
category                                                         edited
query                 Move along, Elf, unless you enjoy making camp ...
reference             Ruszże się elfie, chyba że masz ochotę rozbić ...
edit_type                                                        number
requires_agreement                                                  yes
flag                                                                 ok
comment                                                             NaN
previous_source                                                     NaN
target_approved                                                     NaN
source_file                                                  pl_httt.po
base_id                                67516c582457cc18524ddf1d00349419
source                Move along, Elf, unless you enjoy making camp ...
target                Ruszże się elfie, chyba że masz ochotę rozbić ...
acceptable_ids                       [67516c582457cc18524ddf1d00349419]
Name: 38, dtype: object
case_id                                                             e10
category                                                         edited
query                 When a unit in the front line is heavily damag...
reference             Jeśli jednostka frontowa odniesie poważne obra...
edit_type                                                        gender
requires_agreement                                                  yes
flag                                                                 ok
comment               Switch to gender neutral "them" in the English...
previous_source                                                     NaN
target_approved                                                     NaN
source_file                                                pl_manual.po
base_id                                a2beac7cb6a6c7c968772bfa667e3537
source                When a unit in the front line is heavily damag...
target                Jeśli jednostka frontowa odniesie poważne obra...
acceptable_ids                       [a2beac7cb6a6c7c968772bfa667e3537]
Name: 39, dtype: object
case_id                                                             e11
category                                                         edited
query                 If you control the unit and it hasn&#8217;t mo...
reference             Jeśli masz pod kontrolą jednostkę, która w tej...
edit_type                                                      addition
requires_agreement                                                  yes
flag                                                                 ok
comment                                                             NaN
previous_source                                                     NaN
target_approved                                                     NaN
source_file                                                pl_manual.po
base_id                                2354bf98a635612e1fc01a633a1f07be
source                If you control the unit and it hasn&#8217;t mo...
target                Jednostka pod Twoją kontrolą, która w tej turz...
acceptable_ids                       [2354bf98a635612e1fc01a633a1f07be]
Name: 40, dtype: object
case_id                                                             e12
category                                                         edited
query                 Oh no! They are destroying our home! Where are...
reference             Nie! Oni niszczą nasz dom! Gdzie są bogowie, g...
edit_type                                                      addition
requires_agreement                                                   no
flag                                                                 ok
comment                                                             NaN
previous_source                                                     NaN
target_approved                                                     NaN
source_file                                                  pl_httt.po
base_id                                bc20f15c52179a362ad167f5a3cb84cd
source                             Oh no! They are destroying our home!
target                                       Nie! Oni niszczą nasz dom!
acceptable_ids                       [bc20f15c52179a362ad167f5a3cb84cd]
Name: 41, dtype: object
case_id                                                             e13
category                                                         edited
query                 Click this button to read the previous tips fr...
reference             Kliknij ten przycisk, by przeczytać poprzednie...
edit_type                                                        number
requires_agreement                                                  yes
flag                                                                 ok
comment                                                             NaN
previous_source                                                     NaN
target_approved                                                     NaN
source_file                                                pl_manual.po
base_id                                e15ba18cdc7fe3774e49b3978402f7a9
source                Click this button to read the previous little ...
target                Kliknij ten przycisk, by przeczytać poprzednią...
acceptable_ids                       [e15ba18cdc7fe3774e49b3978402f7a9]
Name: 42, dtype: object
case_id                                                             e14
category                                                         edited
query                    Complete the old <i>Construction</i> tutorial.
reference                       Ukończ stary samouczek <i>Budowanie</i>
edit_type                                                          term
requires_agreement                                                   no
flag                                                       target_error
comment               The original target used inverted commas inste...
previous_source                                                     NaN
target_approved                                                     NaN
source_file                                                  pl_httt.po
base_id                                764c0d9d50cdb8f8a4660ec56b5593f9
source                Complete the old <i>Battle Training</i> tutorial.
target                         Ukończ stary samouczek "Trening bitewny"
acceptable_ids                       [764c0d9d50cdb8f8a4660ec56b5593f9]
Name: 43, dtype: object
case_id                                                            e15
category                                                        edited
query                 Dragons? We were planning to use them as mounts.
reference              Smoki? Planowaliśmy ich użyć jako wierzchowców.
edit_type                                                         term
requires_agreement                                                  no
flag                                                                ok
comment                                                            NaN
previous_source                                                    NaN
target_approved                                                    NaN
source_file                                                 pl_httt.po
base_id                               ff234e2c00e90ab805317597900c9e64
source                 Beasts? We were planning to use them as mounts.
target                Bestie? Planowaliśmy ich użyć jako wierzchowców.
acceptable_ids                      [ff234e2c00e90ab805317597900c9e64]
Name: 44, dtype: object
case_id                                                             e16
category                                                         edited
query                 I think... I think if I were to concentrate a ...
reference             Myślę... Myślę, że jeśli się nieco skoncentruj...
edit_type                                                      addition
requires_agreement                                                   no
flag                                                       target_error
comment                               Original target has missing comma
previous_source                                                     NaN
target_approved                                                     NaN
source_file                                                  pl_httt.po
base_id                                15fdcec8dc0914b6de58c5c9869c2f72
source                I think... I think if I were to concentrate a ...
target                Myślę... Myślę, że jeśli się nieco skoncentruj...
acceptable_ids                       [15fdcec8dc0914b6de58c5c9869c2f72]
Name: 45, dtype: object
case_id                                                             e17
category                                                         edited
query                 You can order a unit to move for multiple turn...
reference                                                           NaN
edit_type                                                           NaN
requires_agreement                                                  NaN
flag                                                                NaN
comment                                                             NaN
previous_source                                                     NaN
target_approved                                                     NaN
source_file                                              pl_tutorial.po
base_id                                19094e83753576c3dc87c3691f935032
source                You can order a unit to move for multiple turn...
target                Możesz sprawić, by jednostka sama się poruszał...
acceptable_ids                       [19094e83753576c3dc87c3691f935032]
Name: 46, dtype: object
case_id                                                             e18
category                                                         edited
query                 Were it not for the armor they wear, certain d...
reference                                                           NaN
edit_type                                                           NaN
requires_agreement                                                  NaN
flag                                                                NaN
comment                                                             NaN
previous_source                                                     NaN
target_approved                                                     NaN
source_file                                                 pl_units.po
base_id                                a09f68a8215f71dbbaa4c37f948f4d8c
source                Were it not for the armor they wear, certain d...
target                Gdyby nie zbroja, niektórych smoczych wojownik...
acceptable_ids                       [a09f68a8215f71dbbaa4c37f948f4d8c]
Name: 47, dtype: object
case_id                                                  e19
category                                              edited
query                    Can’t we just move around the orcs?
reference                                                NaN
edit_type                                                NaN
requires_agreement                                       NaN
flag                                                     NaN
comment                                                  NaN
previous_source                                          NaN
target_approved                                          NaN
source_file                                   pl_tutorial.po
base_id                     aa6c5f79ecd1ae75d30e853834d74ed3
source                   Can’t we just move around the orcs?
target                Czy nie możemy po prostu ominąć orków?
acceptable_ids            [aa6c5f79ecd1ae75d30e853834d74ed3]
Name: 48, dtype: object
case_id                                              e20

In [69]:
# Looping through each row of gold_set_edited

for _, row in gold_set_edited.iterrows():
    query = row['query']
    correct = set(row['acceptable_ids'])
    fuzzy_ids = ranked_ids_fuzzy(query, top_k) # for each row
    semantic_ids = ranked_ids_semantic(query, top_k) # for each row
    # Metrics for fuzzy hits
    fuzzy_hit1 = hit(fuzzy_ids, correct, 1) # was correct in top1?
    fuzzy_hit3 = hit(fuzzy_ids, correct, 3) # was correct in top3?
    fuzzy_hit5 = hit(fuzzy_ids, correct, 5) # was correct in top5?
    fuzzy_rr = reciprocal_rank(fuzzy_ids, correct)
    # Metrics for semantic hits
    semantic_hit1 = hit(semantic_ids, correct, 1) # was correct in top1?
    semantic_hit3 = hit(semantic_ids, correct, 3) # was correct in top3?
    semantic_hit5 = hit(semantic_ids, correct, 5) # was correct in top5?
    semantic_rr = reciprocal_rank(semantic_ids, correct)
    results.append({
        'case_id': row['case_id'],
        'edit_type': row['edit_type'],
        'fuzzy_hit1' : fuzzy_hit1,
        'fuzzy_hit3' : fuzzy_hit3,
        'fuzzy_hit5' : fuzzy_hit5,
        'fuzzy_rr'   : fuzzy_rr,
        'semantic_hit1' : semantic_hit1,
        'semantic_hit3' : semantic_hit3,
        'semantic_hit5' : semantic_hit5,
        'semantic_rr' : semantic_rr
    })
    
print(results[0])

{'case_id': 'e01', 'edit_type': 'term', 'fuzzy_hit1': False, 'fuzzy_hit3': False, 'fuzzy_hit5': False, 'fuzzy_rr': 0.0, 'semantic_hit1': False, 'semantic_hit3': False, 'semantic_hit5': True, 'semantic_rr': 0.2}

In [70]:
# Turning the dictionary into Pandas df
results_df = pd.DataFrame(results)
print(results_df)

   case_id edit_type  fuzzy_hit1  fuzzy_hit3  fuzzy_hit5  fuzzy_rr  \
0      e01      term       False       False       False  0.000000
1      e02  reworded        True        True        True  1.000000
2      e03      term        True        True        True  1.000000
3      e04      term       False       False       False  0.000000
4      e05  reworded       False       False       False  0.000000
5      e06  reworded        True        True        True  1.000000
6      e07    number        True        True        True  1.000000
7      e08    gender        True        True        True  1.000000
8      e09    number        True        True        True  1.000000
9      e10    gender        True        True        True  1.000000
10     e11  addition       False        True        True  0.500000
11     e12  addition        True        True        True  1.000000
12     e13    number        True        True        True  1.000000
13     e14      term        True        True        True  1.000000
14     e15      term        True        True        True  1.000000
15     e16  addition        True        True        True  1.000000
16     e17       NaN        True        True        True  1.000000
17     e18       NaN        True        True        True  1.000000
18     e19       NaN        True        True        True  1.000000
19     e20       NaN        True        True        True  1.000000
20     e21       NaN        True        True        True  1.000000
21     e22  reworded        True        True        True  1.000000
22     e23       NaN        True        True        True  1.000000
23     e24      term       False        True        True  0.333333
24     e25  addition        True        True        True  1.000000
25     e26       NaN        True        True        True  1.000000
26     e27       NaN        True        True        True  1.000000
27     e28      term        True        True        True  1.000000
28     e29      term        True        True        True  1.000000
29     e30    number        True        True        True  1.000000

    semantic_hit1  semantic_hit3  semantic_hit5  semantic_rr
0           False          False           True     0.200000
1            True           True           True     1.000000
2           False           True           True     0.333333
3           False           True           True     0.333333
4           False           True           True     0.333333
5            True           True           True     1.000000
6            True           True           True     1.000000
7            True           True           True     1.000000
8            True           True           True     1.000000
9            True           True           True     1.000000
10           True           True           True     1.000000
11           True           True           True     1.000000
12           True           True           True     1.000000
13          False           True           True     0.333333
14           True           True           True     1.000000
15           True           True           True     1.000000
16           True           True           True     1.000000
17           True           True           True     1.000000
18           True           True           True     1.000000
19           True           True           True     1.000000
20           True           True           True     1.000000
21           True           True           True     1.000000
22           True           True           True     1.000000
23          False           True           True     0.500000
24           True           True           True     1.000000
25           True           True           True     1.000000
26           True           True           True     1.000000
27           True           True           True     1.000000
28           True           True           True     1.000000
29           True           True           True     1.000000

In [71]:
# Adding mean values to the table
results_df.drop(columns=['case_id','edit_type']).mean()

fuzzy_hit1       0.833333
fuzzy_hit3       0.900000
fuzzy_hit5       0.900000
fuzzy_rr         0.861111
semantic_hit1    0.800000
semantic_hit3    0.966667
semantic_hit5    1.000000
semantic_rr      0.867778
dtype: float64

In [73]:
# Grouping the results
results_df.drop(columns=['case_id']).groupby('edit_type').mean()

,fuzzy_hit1,fuzzy_hit3,fuzzy_hit5,fuzzy_rr,semantic_hit1,semantic_hit3,semantic_hit5,semantic_rr
edit_type,,,,,,,,
addition,0.750,1.00,1.00,0.875000,1.000,1.000,1.0,1.000000
gender,1.000,1.00,1.00,1.000000,1.000,1.000,1.0,1.000000
number,1.000,1.00,1.00,1.000000,1.000,1.000,1.0,1.000000
reworded,0.750,0.75,0.75,0.750000,0.750,1.000,1.0,0.833333
term,0.625,0.75,0.75,0.666667,0.375,0.875,1.0,0.587500